#!/bin/sh
HOMEDIR="/home/finitycodejam"
PYTHON="$HOMEDIR/opt/python-3.4.3/bin/python"
CODEDIR="$HOMEDIR/codejam.notmet.net/SecurityTrainingGround"

cd "$CODEDIR"
"$PYTHON" "$CODEDIR/stopScript.py" 1> /dev/null
